-- AUTO-GENERATED by tools/generate_pika_follower_true_size.py -- do not hand-edit.
-- Per-costume art for the PIKA FOLLOWER option (Yellow stock companion only).
-- classicId/relativeDir cover BOTH rendering modes: Classic always uses a fixed
-- 16x16 card (assets/wilds_generated/pika_follower_runtime/<classicId 03d>-normal.png),
-- True Size uses its own native-crop sheet (visual_scale=1.0, no resampling -- same
-- treatment as Pikachu's own real pokemmo/hgss authority pack, since the costume
-- source art shares its exact scale/grid convention) under relativeDir.
return {
  ["alola"] = {classicId=1, frameWidth=22, frameHeight=24, anchorX=11.0, anchorY=22.0, relativeDir="assets/wilds_generated/true_size/pika_alola"},
  ["belle"] = {classicId=2, frameWidth=28, frameHeight=28, anchorX=14.0, anchorY=26.0, relativeDir="assets/wilds_generated/true_size/pika_belle"},
  ["hoenn"] = {classicId=3, frameWidth=22, frameHeight=24, anchorX=11.0, anchorY=22.0, relativeDir="assets/wilds_generated/true_size/pika_hoenn"},
  ["kalos"] = {classicId=4, frameWidth=22, frameHeight=24, anchorX=11.0, anchorY=22.0, relativeDir="assets/wilds_generated/true_size/pika_kalos"},
  ["libre"] = {classicId=5, frameWidth=21, frameHeight=23, anchorX=10.5, anchorY=21.0, relativeDir="assets/wilds_generated/true_size/pika_libre"},
  ["og-cap"] = {classicId=6, frameWidth=22, frameHeight=24, anchorX=11.0, anchorY=22.0, relativeDir="assets/wilds_generated/true_size/pika_og-cap"},
  ["partner"] = {classicId=7, frameWidth=22, frameHeight=24, anchorX=11.0, anchorY=22.0, relativeDir="assets/wilds_generated/true_size/pika_partner"},
  ["phd"] = {classicId=8, frameWidth=34, frameHeight=22, anchorX=17.0, anchorY=20.0, relativeDir="assets/wilds_generated/true_size/pika_phd"},
  ["popstar"] = {classicId=9, frameWidth=21, frameHeight=23, anchorX=10.5, anchorY=21.0, relativeDir="assets/wilds_generated/true_size/pika_popstar"},
  ["rockstar"] = {classicId=10, frameWidth=21, frameHeight=23, anchorX=10.5, anchorY=21.0, relativeDir="assets/wilds_generated/true_size/pika_rockstar"},
  ["sinnoh"] = {classicId=11, frameWidth=22, frameHeight=24, anchorX=11.0, anchorY=22.0, relativeDir="assets/wilds_generated/true_size/pika_sinnoh"},
  ["unova"] = {classicId=12, frameWidth=22, frameHeight=24, anchorX=11.0, anchorY=22.0, relativeDir="assets/wilds_generated/true_size/pika_unova"},
}
