-- PMDCollab / SpriteCollab derived portrait table (dialogue portraits only;
-- the overworld PMDCollab sprite style was removed — see CHANGELOG.md).
-- Generated by scripts/import_pmdcollab.py — never fetch upstream at runtime.
local V = ...

local PmdCollabAssets = {}

local _portraits = nil
local _ready = false
local _loadError = nil

local function loadLuaTable(mod, rel)
  if mod and type(mod.read) == "function" then
    local data = mod:read(rel)
    if type(data) == "string" and data ~= "" then
      local chunk, err = load(data, "@" .. rel)
      if chunk then
        local ok, value = pcall(chunk)
        if ok and type(value) == "table" then
          return value
        end
        return nil, err or "exec failed"
      end
      return nil, err
    end
  end
  local root = (mod and mod.path) or "."
  local path = root .. "/" .. rel
  local chunk, err = loadfile(path)
  if not chunk then
    return nil, err
  end
  local ok, value = pcall(chunk)
  if ok and type(value) == "table" then
    return value
  end
  return nil, "exec failed"
end

function PmdCollabAssets.load(mod)
  if _ready and _portraits then
    return true
  end
  local portraits, pErr = loadLuaTable(mod, "assets/pmdcollab/portrait_table.lua")
  if type(portraits) ~= "table" then
    _loadError = pErr or "portrait_table missing"
    _ready = false
    return false, _loadError
  end
  _portraits = portraits
  _ready = true
  _loadError = nil
  return true
end

function PmdCollabAssets.isReady()
  return _ready == true
end

function PmdCollabAssets.loadError()
  return _loadError
end

--- Reset caches (unit tests).
function PmdCollabAssets.reset()
  _portraits = nil
  _ready = false
  _loadError = nil
end

local function normalizeVariant(variant)
  if variant == true or variant == "shiny" or variant == "s" or variant == "SHINY" then
    return "shiny"
  end
  return "normal"
end

function PmdCollabAssets.dexFor(speciesId)
  local SpeciesAssets = V.require("species_assets")
  return SpeciesAssets.idFor(speciesId)
end

function PmdCollabAssets.portraitEntry(dex, variant)
  if not _ready then return nil end
  dex = tonumber(dex)
  if not dex then return nil end
  local row = _portraits[dex]
  if type(row) ~= "table" then return nil end
  local want = normalizeVariant(variant)
  local entry = row[want]
  if entry then return entry, want end
  if want == "shiny" and row.normal then
    return row.normal, "normal"
  end
  return nil
end

return PmdCollabAssets
