-- Central species visual geometry for True Size (visual only; 1-cell footprint).
-- Data generated by tools/generate_true_size_runtime.py into
-- assets/wilds_generated/true_size/species_table.lua (+ species_geometry.json).
local V = ...
local JsonDecode = V.require("json_decode")
local WildsFs = V.require("wilds_fs")

local SpeciesGeometry = {}

SpeciesGeometry.SIZE_CLASSES = {
  XS  = { minH = 14, maxH = 16, label = "XS" },
  S   = { minH = 17, maxH = 20, label = "S" },
  M   = { minH = 21, maxH = 24, label = "M" },
  L   = { minH = 25, maxH = 29, label = "L" },
  XL  = { minH = 30, maxH = 35, label = "XL" },
  XXL = { minH = 36, maxH = 42, label = "XXL" },
}

-- Visual follower convoy trail gaps (cells). Collision footprint stays 1 cell.
-- Art-direction spacing only — used when True Size effective mode is active.
SpeciesGeometry.FOLLOW_GAP_BY_CLASS = {
  XS = 1,
  S = 1,
  M = 1,
  L = 1,
  XL = 2,
  XXL = 2,
}

-- Manual trail-gap overrides (dex → cells). Prefer readability over literal width.
SpeciesGeometry.FOLLOW_GAP_OVERRIDES = {
  [95] = 3,  -- Onix
  [130] = 3, -- Gyarados
  [131] = 2, -- Lapras
  [143] = 2, -- Snorlax
  [321] = 4, -- Wailord
}

local _displayScaleTable = nil
local _displayScaleStyleOverrides = nil

-- Styles whose art shares the True Size pipeline the base scale table
-- (lib/species_display_scale.lua) was generated from — i.e. their native
-- pixel dimensions were what the table's height data actually measured.
-- A style NOT in this set (PMDCollab: its own independent art asset,
-- confirmed elsewhere to carry no SpeciesGeometry/True Size entry at all)
-- has no relationship to those measurements, so the base table is not a
-- meaningful fallback for it — applying an HGSS-calibrated scale to a
-- differently-sized, unrelated native frame doesn't correct anything, it
-- just distorts a different-sized problem by an unrelated amount.
local TRUE_SIZE_STYLES = {
  pokemmo = true,
  followers = true,
}

--- Shared per-species Voxel display scale (dex → scale, 1 = no change).
-- Drives followers (lib/follower/control_engine.lua), wild spawns
-- (lib/variable_size.lua), and PMDCollab (lib/sprite_providers.lua). See
-- lib/species_display_scale.lua for the full base table.
--
-- style (optional: "pokemmo" | "followers" | "pmdcollab" | ...) looks up
-- lib/species_display_scale_style_overrides.lua first — a species can list
-- a scale just for one style there. If nothing is listed: styles sharing
-- the True Size pipeline (see TRUE_SIZE_STYLES above) fall back to the
-- shared base table; any other style (PMDCollab) falls back to 1 (no
-- change) instead, since the base table was never measured against that
-- style's own native art.
function SpeciesGeometry.displayScale(speciesId, style)
  local dex = SpeciesGeometry.normalizeDex(speciesId)
  if not dex then return 1 end
  if style then
    if _displayScaleStyleOverrides == nil then
      local ok, t = pcall(function()
        return V.require("species_display_scale_style_overrides")
      end)
      _displayScaleStyleOverrides = (ok and type(t) == "table") and t or false
    end
    local perDex = _displayScaleStyleOverrides and _displayScaleStyleOverrides[dex]
    local override = perDex and perDex[style]
    if type(override) == "number" and override > 0 then
      return override
    end
    if not TRUE_SIZE_STYLES[style] then
      return 1
    end
  end
  if _displayScaleTable == nil then
    local ok, t = pcall(function() return V.require("species_display_scale") end)
    _displayScaleTable = (ok and type(t) == "table") and t or false
  end
  local scale = _displayScaleTable and _displayScaleTable[dex]
  if type(scale) == "number" and scale > 0 then return scale end
  return 1
end

--- Resolve the Voxel-only displayWidth/displayHeight/displayAnchorX/
-- displayAnchorY for a real (frameWidth, frameHeight, anchorX, anchorY),
-- honoring the per-species (and optionally per-style) scale above. Returns
-- nil,nil,nil,nil when the resolved scale is 1 or geometry is missing, so
-- callers can uniformly clear their def's display fields in that case.
-- Centralizing this avoids the display fields being computed slightly
-- differently (or forgotten) at any one of the several call sites that
-- build a SpriteDef (follower rebuild paths, wild spawns, PMD provider).
function SpeciesGeometry.resolveDisplayGeometry(speciesId, style, frameWidth, frameHeight, anchorX, anchorY)
  frameWidth = tonumber(frameWidth)
  frameHeight = tonumber(frameHeight)
  if not frameWidth or not frameHeight then return nil, nil, nil, nil end
  local scale = SpeciesGeometry.displayScale(speciesId, style)
  if scale == 1 then return nil, nil, nil, nil end
  local ax = tonumber(anchorX) or (frameWidth / 2)
  local ay = tonumber(anchorY) or frameHeight
  return frameWidth * scale, frameHeight * scale, ax * scale, ay * scale
end

SpeciesGeometry.TABLE_REL = "assets/wilds_generated/true_size/species_table.lua"
SpeciesGeometry.JSON_REL = "assets/wilds_generated/true_size/species_geometry.json"

local _table = nil
local _loadError = nil

local function readBytes(mod, rel)
  return WildsFs.readAsset(mod or V.mod, rel)
end

function SpeciesGeometry.load(mod)
  if _table ~= nil then return _table, _loadError end
  local src = readBytes(mod or V.mod, SpeciesGeometry.TABLE_REL)
  if type(src) == "string" then
    local loader = loadstring or load
    local chunk, err = loader(src, "@" .. SpeciesGeometry.TABLE_REL)
    if chunk then
      local ok, value = pcall(chunk)
      if ok and type(value) == "table" then
        _table = value
        _loadError = nil
        return _table, nil
      end
      _loadError = tostring(value)
    else
      _loadError = tostring(err)
    end
  end
  -- JSON fallback
  local raw = readBytes(mod or V.mod, SpeciesGeometry.JSON_REL)
  if type(raw) == "string" then
    local ok, data = pcall(JsonDecode.decode, raw)
    if ok and type(data) == "table" then
      local converted = {}
      for k, v in pairs(data) do
        local dex = tonumber(k)
        if dex and type(v) == "table" then converted[dex] = v end
      end
      _table = converted
      _loadError = nil
      return _table, nil
    end
  end
  _table = {}
  _loadError = _loadError or "species geometry table missing"
  return _table, _loadError
end

function SpeciesGeometry.clearCache()
  _table = nil
  _loadError = nil
  _displayScaleTable = nil
  _displayScaleStyleOverrides = nil
end

local _cachedMaxSpecies
local function activeMaxSpecies(game)
  local ok, GameCompat = pcall(function() return V.require("game_compat") end)
  if ok and GameCompat and GameCompat.current then
    local adapter = GameCompat.current(nil, game)
    if adapter and type(adapter.MAX_SPECIES) == "number" then
      return adapter.MAX_SPECIES
    end
  end
  if _cachedMaxSpecies then return _cachedMaxSpecies end
  local ok1, Gen1 = pcall(function() return V.require("game_compat/gen1") end)
  if ok1 and Gen1 and type(Gen1.MAX_SPECIES) == "number" then
    _cachedMaxSpecies = Gen1.MAX_SPECIES
  else
    _cachedMaxSpecies = 151
  end
  return _cachedMaxSpecies
end

function SpeciesGeometry.normalizeDex(speciesId, game)
  -- Cap comes from the active generation adapter (Gen1=386, Gen2=386):
  -- Kanto Reforged extends game.data.pokemon to Gen 3 regardless of engine
  -- generation, so geometry lookups are not artificially capped below that.
  local n = tonumber(speciesId)
  if not (n and n >= 1 and math.floor(n) == n) then return nil end
  if n <= activeMaxSpecies(game) then return math.floor(n) end
  return nil
end

function SpeciesGeometry.entryFor(speciesId, mod, game)
  local dex = SpeciesGeometry.normalizeDex(speciesId, game)
  if not dex then return nil, nil end
  local t = SpeciesGeometry.load(mod)
  return t[dex], dex
end

--- Derive a spacing class from native / scaled visual height when present.
local function classFromNativeHeight(h)
  h = tonumber(h) or 0
  if h <= 16 then return "XS" end
  if h <= 20 then return "S" end
  if h <= 24 then return "M" end
  if h <= 29 then return "L" end
  if h <= 35 then return "XL" end
  return "XXL"
end

--- Desired follower trail distance in cells for a species (visual only).
-- Returns 1 when geometry is missing (Classic-equivalent spacing).
-- Prefer explicit FOLLOW_GAP_OVERRIDES, then class from nativeVisualHeight,
-- then legacy entry.class (XS–XXL documentation classes — not HGSS sizing authority).
function SpeciesGeometry.followGap(speciesId, mod)
  local dex = SpeciesGeometry.normalizeDex(speciesId)
  if not dex then return 1 end
  local override = SpeciesGeometry.FOLLOW_GAP_OVERRIDES[dex]
  if type(override) == "number" and override >= 1 then
    return math.floor(override)
  end
  local entry = select(1, SpeciesGeometry.entryFor(dex, mod))
  local class = entry and entry.class or nil
  if entry then
    local nh = tonumber(entry.scaledVisualHeight) or tonumber(entry.nativeVisualHeight)
    if nh and nh > 0 then
      class = classFromNativeHeight(nh)
    end
  end
  class = class or "M"
  local gap = SpeciesGeometry.FOLLOW_GAP_BY_CLASS[class] or 1
  if type(gap) ~= "number" or gap < 1 then gap = 1 end
  return math.floor(gap)
end

--- Spacing between two convoy members: max(gap(previous), gap(current)).
-- previousSpeciesId may be nil (trainer) → uses max(1, gap(current)).
function SpeciesGeometry.followGapBetween(previousSpeciesId, currentSpeciesId, mod)
  local cur = SpeciesGeometry.followGap(currentSpeciesId, mod)
  if previousSpeciesId == nil then
    return math.max(1, cur)
  end
  local prev = SpeciesGeometry.followGap(previousSpeciesId, mod)
  return math.max(prev, cur)
end

-- packId: followers | pokemmo | pokedex | swimming | levitate
function SpeciesGeometry.packGeometry(speciesId, packId, mod)
  local entry, dex = SpeciesGeometry.entryFor(speciesId, mod)
  if not entry or type(entry.packs) ~= "table" then return nil, dex end
  local pack = entry.packs[packId]
  if type(pack) ~= "table" then return nil, dex end
  return pack, dex, entry
end

function SpeciesGeometry.relativePath(speciesId, packId, variant, mod)
  local pack = SpeciesGeometry.packGeometry(speciesId, packId, mod)
  if not pack or type(pack.relativeDir) ~= "string" then return nil end
  local dex = SpeciesGeometry.normalizeDex(speciesId)
  if not dex then return nil end
  local v = (variant == "shiny" or variant == "s" or variant == true) and "shiny" or "normal"
  return string.format("%s/%03d-%s.png", pack.relativeDir, dex, v), pack
end

-- Back-compat alias used by the Charizard prototype.
SpeciesGeometry.prototypeRelativePath = SpeciesGeometry.relativePath
SpeciesGeometry.overrideFor = SpeciesGeometry.entryFor
SpeciesGeometry.OVERRIDES = nil -- deprecated; use generated table

function SpeciesGeometry.summary(mod)
  local t = SpeciesGeometry.load(mod)
  local n, classes, overrides = 0, {}, 0
  for dex, e in pairs(t) do
    if type(dex) == "number" and type(e) == "table" then
      n = n + 1
      local c = e.class or "?"
      classes[c] = (classes[c] or 0) + 1
      if e.manualOverride then overrides = overrides + 1 end
    end
  end
  return {
    species = n,
    classes = classes,
    manualOverrides = overrides,
    loadError = _loadError,
  }
end

return SpeciesGeometry
