#!/usr/bin/env python3
"""Import PMDCollab/SpriteCollab dialogue portraits into Wilds runtime packs.

Developer supplies a local SpriteCollab checkout. This script NEVER clones or
downloads at runtime — Wilds ships only the derived assets under
assets/pmdcollab/.

Portraits power Gen2 dialogue only (lib/portrait_registry.lua). The overworld
PMDCollab sprite style was removed — see CHANGELOG.md — so this importer no
longer builds walker sheets.

Usage:
  python3 scripts/import_pmdcollab.py /path/to/SpriteCollab
  python3 scripts/import_pmdcollab.py ../SpriteCollab --dex-max 251

Output:
  assets/pmdcollab/portraits/{dex:03d}/{variant}/{emotion}.png
  assets/pmdcollab/portrait_table.lua
  assets/pmdcollab/SOURCE.json
  assets/pmdcollab/LICENSE.txt
  assets/pmdcollab/CREDITS.txt
  THIRD_PARTY_ASSETS.md (repo root, updated section)
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

from PIL import Image

IMPORTER_VERSION = "4"
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "pmdcollab"

# Safe generic dialogue emotions (never Pain/Sad/Crying/Dizzy/etc.).
SAFE_EMOTIONS = (
    "Normal",
    "Happy",
    "Joyous",
    "Inspired",
    "Determined",
)
# Filename slug for runtime (lowercase, no spaces).
EMOTION_SLUG = {
    "Normal": "normal",
    "Happy": "happy",
    "Joyous": "joyous",
    "Inspired": "inspired",
    "Determined": "determined",
}

GENERIC_POOL = ("happy", "joyous", "inspired", "determined", "normal")


def fail(msg: str) -> None:
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def verify_source(src: Path) -> None:
    if not src.is_dir():
        fail(f"SpriteCollab path not found: {src}")
    for req in ("LICENSE.md", "sprite", "portrait", "sprite_config.json"):
        if not (src / req).exists():
            fail(
                f"Not a SpriteCollab checkout (missing {req}). "
                f"Pass the path to a local clone of "
                f"https://github.com/PMDCollab/SpriteCollab"
            )


def git_sha(src: Path) -> str | None:
    """HEAD of SpriteCollab checkout only (not a parent unrelated repo)."""
    try:
        top = subprocess.check_output(
            ["git", "-C", str(src), "rev-parse", "--show-toplevel"],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
        if not top:
            return None
        # Fixture folders nested in Wilds must not report Wilds' SHA.
        if not (Path(top) / "sprite").is_dir() or not (Path(top) / "portrait").is_dir():
            return None
        out = subprocess.check_output(
            ["git", "-C", str(src), "rev-parse", "HEAD"],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
        return out or None
    except (subprocess.CalledProcessError, FileNotFoundError, OSError):
        return None


def read_credits_authors(credits_path: Path, wanted: set[str]) -> list[str]:
    """Return unique CUR author ids for matching asset names."""
    if not credits_path.is_file():
        return []
    authors: list[str] = []
    seen: set[str] = set()
    for line in credits_path.read_text(encoding="utf-8", errors="replace").splitlines():
        parts = line.split("\t")
        if len(parts) < 5:
            continue
        _dt, author, status, _lic, assets = parts[0], parts[1], parts[2], parts[3], parts[4]
        if status.strip().upper() == "OLD":
            continue
        asset_names = {a.strip() for a in assets.split(",") if a.strip()}
        if wanted and asset_names.isdisjoint(wanted):
            continue
        a = author.strip()
        if a and a not in seen:
            seen.add(a)
            authors.append(a)
    return authors


def load_credit_names(src: Path) -> dict[str, tuple[str, str]]:
    """author_id -> (display_name, contact)."""
    path = src / "credit_names.txt"
    out: dict[str, tuple[str, str]] = {}
    if not path.is_file():
        return out
    for i, line in enumerate(path.read_text(encoding="utf-8", errors="replace").splitlines()):
        if i == 0 and line.startswith("Name"):
            continue
        parts = line.split("\t")
        if len(parts) < 1:
            continue
        name = parts[0].strip()
        discord = parts[1].strip() if len(parts) > 1 else ""
        contact = parts[2].strip() if len(parts) > 2 else ""
        if name:
            out[name] = (name, contact)
        if discord:
            out[discord] = (name or discord, contact)
    return out


def lua_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def write_portrait_table(path: Path, portraits: dict[int, dict], source_sha: str | None) -> None:
    lines = [
        "-- AUTO-GENERATED by scripts/import_pmdcollab.py — do not hand-edit.",
        f"-- Importer version {IMPORTER_VERSION}. Source SHA: {source_sha or 'unknown'}",
        "return {",
    ]
    for dex in sorted(portraits):
        entry = portraits[dex]
        lines.append(f"  [{dex}]={{")
        for variant in ("normal", "shiny"):
            v = entry.get(variant)
            if not v:
                continue
            emo_parts = []
            for slug, rel in sorted(v["emotions"].items()):
                emo_parts.append(f'{slug}="{lua_escape(rel)}"')
            lines.append(
                f'    {variant}={{emotions={{{",".join(emo_parts)}}},'
                f'sourcePath="{lua_escape(v.get("sourcePath") or "")}"}},'
            )
        lines.append("  },")
    lines.append("}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def save_png(im: Image.Image, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    im.save(path, format="PNG", optimize=True)


def import_species_portraits(
    src: Path,
    dex: int,
    credit_acc: dict[str, set[str]],
) -> dict | None:
    folder = f"{dex:04d}"
    portrait_dir = src / "portrait" / folder
    portrait_out: dict = {}

    # Portraits: root for normal; 0000/0001 for shiny when present.
    for shiny in (False, True):
        variant = "shiny" if shiny else "normal"
        pdir = portrait_dir / "0000" / "0001" if shiny else portrait_dir
        if not pdir.is_dir():
            continue
        emotions: dict[str, str] = {}
        for emo_name, slug in EMOTION_SLUG.items():
            src_png = pdir / f"{emo_name}.png"
            if not src_png.is_file():
                continue
            im = Image.open(src_png).convert("RGBA")
            rel = f"assets/pmdcollab/portraits/{dex:03d}/{variant}/{slug}.png"
            save_png(im, ROOT / rel)
            emotions[slug] = rel
        if not emotions:
            continue
        portrait_out[variant] = {
            "emotions": emotions,
            "sourcePath": str(pdir.relative_to(src)).replace("\\", "/"),
        }
        for author in read_credits_authors(pdir / "credits.txt", set(EMOTION_SLUG.keys())):
            credit_acc[author].add(f"portrait/{folder} {variant}")

    return portrait_out or None


def write_credits(
    out_path: Path,
    src: Path,
    sha: str | None,
    credit_names: dict[str, tuple[str, str]],
    credit_acc: dict[str, set[str]],
) -> None:
    lines = [
        "PMDCollab / SpriteCollab attribution for Wilds of Kanto derived assets",
        "=" * 72,
        "",
        "Source: https://github.com/PMDCollab/SpriteCollab",
        f"Revision: {sha or 'unknown'}",
        "License: Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)",
        "License URI: https://creativecommons.org/licenses/by-nc/4.0/",
        "Browse: http://sprites.pmdcollab.org/",
        "",
        "Wilds redistributes selected Gen1-Gen2 portrait emotions from",
        "SpriteCollab, used for Pokemon dialogue. Official Chunsoft-origin art",
        "may appear with credit id CHUNSOFT (license field often Unspecified",
        "upstream).",
        "",
        "Contributor credits below are taken from upstream credit_names.txt and",
        "per-folder credits.txt (CUR entries only). Author names are not invented.",
        "",
        "Contributors referenced by imported assets:",
        "",
    ]
    for author in sorted(credit_acc.keys(), key=lambda a: a.lower()):
        display, contact = credit_names.get(author, (author, ""))
        lines.append(f"- {display}")
        if author != display:
            lines.append(f"  id: {author}")
        if contact:
            lines.append(f"  contact: {contact}")
        # Cap contribution list length for readability
        contribs = sorted(credit_acc[author])
        if len(contribs) > 12:
            shown = contribs[:12] + [f"... +{len(contribs) - 12} more"]
        else:
            shown = contribs
        lines.append(f"  assets: {', '.join(shown)}")
        lines.append("")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_third_party_md(sha: str | None) -> None:
    path = ROOT / "THIRD_PARTY_ASSETS.md"
    body = f"""# Third-Party Assets — PMDCollab / SpriteCollab

## Source

- Repository: [PMDCollab/SpriteCollab](https://github.com/PMDCollab/SpriteCollab)
- Browse: http://sprites.pmdcollab.org/
- Imported revision: `{sha or "unknown"}`
- Importer: `scripts/import_pmdcollab.py` (version {IMPORTER_VERSION})

## License

SpriteCollab materials are licensed under **Creative Commons
Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)**.

- Full license text shipped at `assets/pmdcollab/LICENSE.txt`
- Upstream: https://creativecommons.org/licenses/by-nc/4.0/

Non-commercial use only. Attribution required. See upstream LICENSE.md and
README use policy.

Official Chunsoft-origin graphics that appear in SpriteCollab are credited as
`CHUNSOFT` in upstream `credits.txt` (license field often `Unspecified`).

## What Wilds redistributes

Under `assets/pmdcollab/` Wilds ships **derived** dialogue-portrait assets
only:

- Selected portrait emotions for Pokémon dialogue (Normal + safe generic pool)
- Generated metadata table and contributor credits

Wilds does **not** ship the full SpriteCollab repository, XML sources,
overworld walker sprites, or dungeon-only animations.

## Attribution

See `assets/pmdcollab/CREDITS.txt` for contributor credits collected from
upstream `credit_names.txt` and per-folder `credits.txt`.

Also listed in `THIRD_PARTY_NOTICES.md`.
"""
    path.write_text(body, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("source", type=Path, help="Path to local SpriteCollab checkout")
    ap.add_argument("--dex-min", type=int, default=1)
    ap.add_argument("--dex-max", type=int, default=251)
    ap.add_argument("--clean", action="store_true", help="Remove prior portraits output")
    args = ap.parse_args()

    src = args.source.resolve()
    verify_source(src)
    sha = git_sha(src)
    credit_names = load_credit_names(src)

    if args.clean and OUT.exists():
        import shutil

        p = OUT / "portraits"
        if p.exists():
            shutil.rmtree(p)

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "portraits").mkdir(exist_ok=True)

    # License copy (exact upstream text).
    license_src = src / "LICENSE.md"
    (OUT / "LICENSE.txt").write_bytes(license_src.read_bytes())

    portrait_table: dict[int, dict] = {}
    credit_acc: dict[str, set[str]] = defaultdict(set)
    missing_portrait: list[int] = []

    for dex in range(args.dex_min, args.dex_max + 1):
        por = import_species_portraits(src, dex, credit_acc)
        if not por or "normal" not in por:
            missing_portrait.append(dex)
        else:
            portrait_table[dex] = por

    write_portrait_table(OUT / "portrait_table.lua", portrait_table, sha)
    write_credits(OUT / "CREDITS.txt", src, sha, credit_names, credit_acc)
    write_third_party_md(sha)

    source_info = {
        "repository": "https://github.com/PMDCollab/SpriteCollab",
        "commit": sha,
        "importerVersion": IMPORTER_VERSION,
        "dexMin": args.dex_min,
        "dexMax": args.dex_max,
        "safePortraitEmotions": list(EMOTION_SLUG.values()),
        "genericEmotionPool": list(GENERIC_POOL),
        "portraitsImported": len(portrait_table),
        "missingPortraitNormal": missing_portrait,
    }
    (OUT / "SOURCE.json").write_text(
        json.dumps(source_info, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    # Size report
    portrait_files = list((OUT / "portraits").rglob("*.png"))
    total = sum(p.stat().st_size for p in portrait_files)
    total += sum(
        (OUT / name).stat().st_size
        for name in (
            "portrait_table.lua",
            "SOURCE.json",
            "LICENSE.txt",
            "CREDITS.txt",
        )
        if (OUT / name).is_file()
    )

    print("import_pmdcollab: ok")
    print(f"  source: {src}")
    print(f"  commit: {sha or 'unknown'}")
    print(f"  species with portraits: {len(portrait_table)}")
    print(f"  portrait PNGs: {len(portrait_files)}")
    print(f"  total bytes: {total} ({total / 1024 / 1024:.2f} MiB)")
    if missing_portrait:
        print(f"  missing portraits: count={len(missing_portrait)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
