#!/usr/bin/env python3
"""Generate lib/species_flags_data.lua: the species RANDOM spawn mode leaves out by default.

Reads a PokeAPI-style `pokemon_species.csv` (columns include `id`, `identifier`, `is_legendary`,
`is_mythical`; `id` is the national dex number) and writes the restricted set keyed by national dex:

    restricted = { [dex] = "legendary" | "mythical" | "ultra_beast" | "paradox" }

Legendary/mythical come straight from the CSV flags. Ultra Beasts and Paradox Pokemon carry no flag
there, so they are listed by dex below and verified against the CSV identifiers (a wrong id fails the
run instead of silently restricting the wrong species). Koraidon/Miraidon are already `is_legendary`.

    python3 tools/generate_species_flags.py --species-csv <pokemon_species.csv>
"""
import argparse
import csv
import sys
from pathlib import Path

ULTRA_BEASTS = {
    793: "nihilego", 794: "buzzwole", 795: "pheromosa", 796: "xurkitree", 797: "celesteela",
    798: "kartana", 799: "guzzlord", 803: "poipole", 804: "naganadel", 805: "stakataka",
    806: "blacephalon",
}

PARADOX = {
    984: "great-tusk", 985: "scream-tail", 986: "brute-bonnet", 987: "flutter-mane",
    988: "slither-wing", 989: "sandy-shocks", 990: "iron-treads", 991: "iron-bundle",
    992: "iron-hands", 993: "iron-jugulis", 994: "iron-moth", 995: "iron-thorns",
    1005: "roaring-moon", 1006: "iron-valiant", 1009: "walking-wake", 1010: "iron-leaves",
    1020: "gouging-fire", 1021: "raging-bolt", 1022: "iron-boulder", 1023: "iron-crown",
}

DEFAULT_OUT = Path(__file__).resolve().parent.parent / "lib" / "species_flags_data.lua"


def load_species(path):
    rows = {}
    with open(path, encoding="utf-8", newline="") as fh:
        for row in csv.DictReader(fh):
            rows[int(row["id"])] = row
    return rows


def classify(rows):
    restricted, problems = {}, []
    for dex, row in sorted(rows.items()):
        if row.get("is_mythical") == "1":
            restricted[dex] = "mythical"
        elif row.get("is_legendary") == "1":
            restricted[dex] = "legendary"
    for label, table in (("ultra_beast", ULTRA_BEASTS), ("paradox", PARADOX)):
        for dex, ident in table.items():
            row = rows.get(dex)
            if row is None or row["identifier"] != ident:
                problems.append(f"{label} #{dex} expected {ident!r}, CSV has {row and row['identifier']!r}")
            elif dex in restricted:
                problems.append(f"{label} #{dex} {ident} is already {restricted[dex]} in the CSV")
            else:
                restricted[dex] = label
    return restricted, problems


def render(restricted, rows):
    lines = [
        "-- GENERATED by tools/generate_species_flags.py from a PokeAPI pokemon_species.csv. Do not edit.",
        "-- National dex numbers that RANDOM spawn mode leaves out unless \"Include Legendary/Mythical\" is on.",
        "return {",
        "  version = 1,",
        "  restricted = {",
    ]
    for dex in sorted(restricted):
        lines.append(f'    [{dex}] = "{restricted[dex]}", -- {rows[dex]["identifier"]}')
    lines += ["  },", "}", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--species-csv", required=True, type=Path)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    rows = load_species(args.species_csv)
    restricted, problems = classify(rows)
    if problems:
        print("\n".join(problems), file=sys.stderr)
        return 1
    args.out.write_text(render(restricted, rows), encoding="utf-8", newline="\n")

    counts = {}
    for kind in restricted.values():
        counts[kind] = counts.get(kind, 0) + 1
    print(f"wrote {args.out} ({len(restricted)} species): "
          + ", ".join(f"{k}={counts[k]}" for k in sorted(counts)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
