#!/usr/bin/env python3
"""Bake True Size art for the 12 PIKA FOLLOWER costume options (Yellow stock companion only).

Each costume source PNG is the SAME scale/grid convention as Pikachu's own real followsprites
art (128x128, 4x4 grid of 32x32 tiles) -- not a secondary pack that needs visually matching to
some other reference. So this bakes them the same way generate_true_size_runtime.py's
generate_hgss_for_dex treats Pikachu's own real art: a native pixel crop at visual_scale=1.0
with allow_resample=False (no forced resizing at all), NOT generate_matched_pack_for_dex's
"resample to match a reference visible height" path (that path is for genuinely secondary packs
like followers/pokedex that DO need fitting against the hgss authority).

An earlier version of this script routed through generate_matched_pack_for_dex, which forced an
NN resample to a target height read from dex 25's own species_geometry.json entry -- but that
entry's nativeVisualHeight/scaledVisualHeight are None (Pikachu is one of the species still on
the older "legacy_target_height" sizing method), so the fallback silently landed on a hardcoded
16px target, well under Pikachu's real ~18px frame, and every costume got needlessly downscaled
and blurred. Baking natively (this version) sidesteps needing any reference value at all.

Critical: this never calls back into generate_true_size_runtime.py's own persistence
(write_species_geometry_lua / species_table.lua writes) -- the shared True Size tables are never
touched. Output PNGs land under assets/wilds_generated/true_size/pika_<name>/025-normal.png (one
subfolder per costume, non-colliding with any real pack); the resulting per-costume
frameWidth/frameHeight/anchorX/anchorY is written to lib/pika_follower_geometry.lua for the
runtime Lua resolver to read directly (no JSON parsing needed at runtime).

Run: python3 tools/generate_pika_follower_true_size.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))
import generate_true_size_runtime as gts  # noqa: E402

MAPPING = ROOT / "assets/enhanced_overworld/pika_follower_mapping/pika_follower_mapping.json"
LUA_OUT = ROOT / "lib/pika_follower_geometry.lua"


def main() -> int:
    if not MAPPING.is_file():
        print(f"error: mapping missing: {MAPPING}", file=sys.stderr)
        return 1

    data = json.loads(MAPPING.read_text(encoding="utf-8"))
    layout = data.get("layout") or gts.DEFAULT_LAYOUT
    species = data.get("species") or {}

    results: dict[str, dict] = {}
    written = 0
    errors = 0

    for _key, entry_data in sorted(species.items(), key=lambda kv: int(kv[0])):
        classic_id = int(_key)
        name = entry_data.get("name")
        normal = entry_data.get("normal") or {}
        src_rel = normal.get("path")
        if not (name and src_rel):
            continue
        src = ROOT / src_rel
        if not src.is_file():
            print(f"WARN: missing source art for {name}: {src}", file=sys.stderr)
            errors += 1
            continue

        pack = f"pika_{name}"
        out_dir = gts.OUT_ROOT / pack
        out_dir.mkdir(parents=True, exist_ok=True)

        im = Image.open(src).convert("RGBA")
        cols = int(layout.get("columns", 4))
        rows = int(layout.get("rows", 4))
        tw, th = im.width // cols, im.height // rows
        tiles = gts.extract_grid_tiles(im, layout, tw, th)

        cards, meta = gts.compose_native_sheet(
            tiles, padding=gts.TRUE_SIZE_PADDING, visual_scale=1.0, allow_resample=False)
        fw, fh = meta["runtimeFrameWidth"], meta["runtimeFrameHeight"]

        out_path = out_dir / "025-normal.png"
        sheet = gts.stack_sheet(cards, fw, fh)
        sheet.save(out_path, optimize=True)

        results[name] = {
            "classicId": classic_id,
            "frameWidth": fw,
            "frameHeight": fh,
            "anchorX": meta["anchorX"],
            "anchorY": meta["anchorY"],
            "relativeDir": f"assets/wilds_generated/true_size/{pack}",
        }
        written += 1

    lines = [
        "-- AUTO-GENERATED by tools/generate_pika_follower_true_size.py -- do not hand-edit.",
        "-- Per-costume art for the PIKA FOLLOWER option (Yellow stock companion only).",
        "-- classicId/relativeDir cover BOTH rendering modes: Classic always uses a fixed",
        "-- 16x16 card (assets/wilds_generated/pika_follower_runtime/<classicId 03d>-normal.png),",
        "-- True Size uses its own native-crop sheet (visual_scale=1.0, no resampling -- same",
        "-- treatment as Pikachu's own real pokemmo/hgss authority pack, since the costume",
        "-- source art shares its exact scale/grid convention) under relativeDir.",
        "return {",
    ]
    for name in sorted(results.keys()):
        g = results[name]
        lines.append(
            '  ["%s"] = {classicId=%s, frameWidth=%s, frameHeight=%s, anchorX=%s, anchorY=%s, '
            'relativeDir="%s"},' % (
                name, g["classicId"], g["frameWidth"], g["frameHeight"], g["anchorX"],
                g["anchorY"], g["relativeDir"],
            )
        )
    lines.append("}")
    lines.append("")
    LUA_OUT.write_text("\n".join(lines), encoding="utf-8")

    print(f"pika_follower true size: written={written} errors={errors} -> {LUA_OUT}")
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
